language: go

go:
  - 1.4.3
  - 1.5.3
  - 1.6
  - tip

os:
  - linux
  - osx

sudo: false

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v pkg.re/check.v1
  - go get -v pkg.re/essentialkaos/ek.v1

script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./parser
  - go build shdoc.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
