sudo: false

language: go

go:
  - 1.6.3
  - 1.7.1
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v pkg.re/check.v1
  - go get -v pkg.re/essentialkaos/ek.v5

script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./parser
  - go build shdoc.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
