################################################################################

# This Makefile generated by GoMakeGen 1.1.0 using next command:
# gomakegen --race .
#
# More info: https://kaos.sh/gomakegen

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt all clean git-config deps deps-test test gen-fuzz help

################################################################################

all: shdoc ## Build all binaries

shdoc: ## Build shdoc binary
	go build shdoc.go

install: ## Install all binaries
	cp shdoc /usr/bin/shdoc

uninstall: ## Uninstall all binaries
	rm -f /usr/bin/shdoc

git-config: ## Configure git redirects for stable import path services
	git config --global http.https://pkg.re.followRedirects true

deps: git-config ## Download dependencies
	go get -d -v pkg.re/essentialkaos/ek.v10

deps-test: git-config ## Download dependencies for tests
	go get -d -v pkg.re/check.v1

test: ## Run tests
	go test -race ./parser
	go test -covermode=count ./parser

gen-fuzz: ## Generate archives for fuzz testing
	which go-fuzz-build &>/dev/null || go get -u -v github.com/dvyukov/go-fuzz/go-fuzz-build
	go-fuzz-build -o parser-fuzz.zip github.com/essentialkaos/shdoc/parser

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

clean: ## Remove generated files
	rm -f shdoc

help: ## Show this info
	@echo -e '\n\033[1mSupported targets:\033[0m\n'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[33m%-12s\033[0m %s\n", $$1, $$2}'
	@echo -e ''
	@echo -e '\033[90mGenerated by GoMakeGen 1.1.0\033[0m\n'

################################################################################
